### ISSUE TITLE
Not possible to export locations

### ISSUE THREAD

**Issue by KasperFranz** [mejrs/rs3cache#7]
When I try to export locations I get the following error

> kasper@MBP output % rs3 --input CACHE_LOCATION --output . --dump locations
   Dumping [                              ] 0/1: locations_by_id                                                                                                                                     thread 'main' panicked at /Users/kasper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.6.0/src/lib.rs:137:5:
advance out of bounds: the len is 0 but advancing by 1
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: bytes::panic_advance
   3: ndarray::iterators::to_vec_mapped
   4: rs3cache::definitions::mapsquares::MapSquare::from_archive
   5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   6: rs3cache::definitions::mapsquares::export_locations_by_id
   7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   8: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
  10: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  11: rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  12: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter
  13: rs3cache::impl_::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

I have installed it with cargo and I am running macos

**Comment by mejrs** [comment]
I have pushed some updates, can you try it now? it works with the latest rs3 cache on my end.

**Comment by KasperFranz** [comment]
Works as expected - thank you for the quick turnaround
